---

  - name: 5.1.1 Ensure cron daemon is enabled (Scored)
    service:
      name: cron
      state: started
      enabled: yes
    tags:
      - section5
      - section5.1
      - section5.1.1

  - name: 5.1.2 Ensure permissions on /etc/crontab are configured (Scored)
    file:
      path: /etc/crontab
      owner: root
      group: root
      mode: 0600
    tags:
      - section5
      - section5.1
      - section5.1.2

  - name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured (Scored)
    file:
      path: /etc/cron.hourly
      owner: root
      group: root
      mode: 0600
    tags:
      - section5
      - section5.1
      - section5.1.3

  - name: 5.1.4 Ensure permissions on /etc/cron.daily are configured (Scored)
    file:
      path: /etc/cron.daily
      owner: root
      group: root
      mode: 0600
    tags:
      - section5
      - section5.1
      - section5.1.4

  - name: 5.1.5 Ensure permissions on /etc/cron.weekly are configured (Scored)
    file:
      path: /etc/cron.weekly
      owner: root
      group: root
      mode: 0600
    tags:
      - section5
      - section5.1
      - section5.1.5

  - name: 5.1.6 Ensure permissions on /etc/cron.monthly are configured (Scored)
    file:
      path: /etc/cron.monthly
      owner: root
      group: root
      mode: 0600
    tags:
      - section5
      - section5.1
      - section5.1.6

  - name: 5.1.7 Ensure permissions on /etc/cron.d are configured (Scored)
    file:
      path: /etc/cron.monthly
      state: directory
      owner: root
      group: root
      mode: 0600

    tags:
      - section5
      - section5.1
      - section5.1.7

  - name: 5.1.8 Ensure at/cron is restricted to authorized users (Scored)
    file:
      path: "{{ item.name }}"
      owner: root
      group: root
      mode: 0600
      state: "{{ item.state }}"
    with_items:
      - { name: '/etc/cron.deny' , state: 'absent' }
      - { name: '/etc/at.deny' , state: 'absent' }
      - { name: '/etc/cron.allow' , state: 'touch' }
      - { name: '/etc/at.allow' , state: 'touch' }
    tags:
      - section5
      - section5.1
      - section5.1.8
