---

  - shell: dpkg --get-selections | grep -v deinstall | awk '{ print $1 }'
    register: dpkg_output
    tags:
      - section6
      - section6.1
      - section6.1.1

  - name: 6.1.1 Audit system file permissions (Not Scored) 
    shell: dpkg --verify {{ item }}
    with_items: "{{ dpkg_output.stdout_lines }}"
    when: dpkg_verify == True
    tags:
      - section6
      - section6.1
      - section6.1.1
    
  - name: 6.1.2 Ensure permissions on /etc/passwd are configured (Scored)
    file:
      path: /etc/passwd
      mode: 0644
      owner: root
      group: root
    tags:
      - section6
      - section6.1
      - section6.1.2

  - name: 6.1.3 Ensure permissions on /etc/shadow are configured (Scored)
    file:
      path: /etc/shadow
      mode: 0640
      owner: root
      group: root
    tags:
      - section6
      - section6.1
      - section6.1.3

  - name: 6.1.4 Ensure permissions on /etc/group are configured (Scored)
    file:
      path: /etc/group
      mode: 0644
      owner: root
      group: root
    tags:
      - section6
      - section6.1
      - section6.1.4

  - name: 6.1.5 Ensure permissions on /etc/gshadow are configured (Scored)
    file:
      path: /etc/gshadow
      mode: 0640
      owner: root
      group: root
    tags:
      - section6
      - section6.1
      - section6.1.5

  - name: 6.1.6 Ensure permissions on /etc/passwd- are configured (Scored)
    file:
      path: /etc/passwd-
      mode: 0600
      owner: root
      group: root
    tags:
      - section6
      - section6.1
      - section6.1.6

  - name: 6.1.7 Ensure permissions on /etc/shadow- are configured (Scored)
    file:
      path: /etc/shadow-
      mode: 0600
      owner: root
      group: root
    tags:
      - section6
      - section6.1
      - section6.1.7

  - name: 6.1.8 Ensure permissions on /etc/group- are configured (Scored)
    file:
     path: /etc/group-
     mode: 0600
     owner: root
     group: root
    tags:
      - section6
      - section6.1
      - section6.1.8

  - name: 6.1.9 Ensure permissions on /etc/gshadow- are configured (Scored)
    file:
      path: /etc/gshadow-
      mode: 0600
      owner: root
      group: root
    tags:
      - section6
      - section6.1
      - section6.1.9

  - name: 6.1.10 Ensure no world writable files exist (Scored)
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002 -print
    changed_when: False
    failed_when: False
    check_mode: no
    register: world_files
    tags:
      - section6
      - section6.1
      - section6.1.10

  - name: 6.1.10 Ensure no world writable files exist (Scored)
    debug: "{{ item }}"
    with_items: "{{world_files.stdout_lines}}"
    tags:
      - section6
      - section6.1
      - section6.1.10

  - name: 6.1.11 Ensure no unowned files or directories exist (Scored)
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser -ls
    changed_when: False
    failed_when: False
    check_mode: no
    register: unowned_files
    tags:
      - section6
      - section6.1
      - section6.1.11

  - name: 6.1.11 Ensure no unowned files or directories exist (Scored)
    debug: "{{ item }}"
    with_items: "{{unowned_files.stdout_lines}}"
    tags:
      - section6
      - section6.1
      - section6.1.11

  - name: 6.1.12 Ensure no ungrouped files or directories exist (Scored)
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nogroup -ls
    changed_when: False
    failed_when: False
    check_mode: no
    register: ungrouped_files
    tags:
      - section6
      - section6.1
      - section6.1.12

  - name: 6.1.12 Ensure no ungrouped files or directories exist (Scored)
    debug: "{{ item }}"
    with_items: "{{ungrouped_files.stdout_lines}}"
    tags:
      - section6
      - section6.1
      - section6.1.12

  - shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -4000 -print
    changed_when: False
    failed_when: False
    check_mode: no
    register: suid_files
    tags:
      - section6
      - section6.1
      - section6.1.13

  - name: 6.1.13 Audit SUID executables (Not Scored)
    debug:
      msg: "Audit SUID {{ item }}"
    with_items: "{{suid_files.stdout_lines}}"
    tags:
      - section6
      - section6.1
      - section6.1.13

  - shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -2000 -print
    changed_when: False
    failed_when: False
    check_mode: no
    register: gsuid_files
    tags:
      - section6
      - section6.1
      - section6.1.14

  - name: 6.1.14 Audit SGID executables (Not Scored)
    debug:
      msg: "Audit SGID {{ item }}"
    with_items: "{{gsuid_files.stdout_lines}}"
    tags:
      - section6
      - section6.1
      - section6.1.14
