---

  - name: 1.3.1 Ensure AIDE is installed (Scored)
    apt:
      name: aide
      state: present
    register: aide_installed
    when: use_aide == True
    tags:
      - section1
      - section1.3
      - section1.3.1

  - name: 1.3.2 Ensure filesystem integrity is regularly checked (Scored)
    cron:
      name: "Check files integrity"
      minute: 0
      hour: 5
      job: "/usr/bin/aide --check"
    when: use_aide == True
    tags:
      - section1
      - section1.3
      - section1.3.2
