---

  - apt:
      name: rfkill
      state: present
    tags:
      - section3
      - section3.7

  - name: 3.7 Ensure wireless interfaces are disabled (Not Scored)
    command: rfkill block wifi
    when: disable_wifi == True
    tags:
      - section3
      - section3.7
