---

  - apt:
      name: auditd
      state: present
    when: enable_auditd == True
    tags:
      - section4
      - section4.1
      - section4.1.1.1

  - name: 4.1.1.1 Ensure audit log storage size is configured (Not Scored)
    lineinfile: 
        dest: /etc/audit/auditd.conf
        line: 'max_log_file = {{max_log_file_auditd}}'
        state: present
        create: yes
    when: enable_auditd == True
    tags:
      - section4
      - section4.1
      - section4.1.1.1

  - name: 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)
    lineinfile:
        dest: /etc/audit/auditd.conf
        line: '{{ item.name }} = {{ item.value }}'
        state: present
        create: yes
    with_items:
        - { name: 'space_left_action' , value: 'email' } 
        - { name: 'action_mail_acct' , value: 'root' }
        - { name: 'admin_space_left_action' , value: 'halt' }
    when: enable_auditd == True
    tags:
      - section4
      - section4.1
      - section4.1.1.2

  - name: 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)
    lineinfile:
        dest: /etc/audit/auditd.conf
        line: 'max_log_file_action = keep_logs'
        state: present
        create: yes
    when: enable_auditd == True
    tags:
      - section4
      - section4.1
      - section4.1.1.3

  - name: 4.1.2 Ensure auditd service is enabled (Scored)
    service:
        name: auditd
        enabled: yes
    when: enable_auditd == True
    tags:
      - section4
      - section4.1
      - section4.1.2

  - name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
    lineinfile:
        dest: /etc/default/grub
        line: 'GRUB_CMDLINE_LINUX="audit=1"'
    tags:
      - section4
      - section4.1
      - section4.1.3

  - name: 4.1.4 Ensure events that modify date and time information are collected (Scored)
    lineinfile: 
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change'
      - '-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change'
      - '-a always,exit -F arch=b64 -S clock_settime -k time-change'
      - '-a always,exit -F arch=b32 -S clock_settime -k time-change'
      - '-w /etc/localtime -p wa -k time-change'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.4

  - name: 4.1.5 Ensure events that modify user/group information are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes    
    with_items:
      - '-w /etc/group -p wa -k identity'
      - '-w /etc/passwd -p wa -k identity'
      - '-w /etc/gshadow -p wa -k identity'
      - '-w /etc/shadow -p wa -k identity'
      - '-w /etc/security/opasswd -p wa -k identity'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.5

  - name: 4.1.6 Ensure events that modify the system's network environment are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-a exit,always -F arch=b32 -S sethostname -S setdomainname -k system-locale'
      - '-a exit,always -F arch=b64 -S sethostname -S setdomainname -k system-locale'
      - '-w /etc/issue -p wa -k system-locale'
      - '-w /etc/issue.net -p wa -k system-locale'
      - '-w /etc/hosts -p wa -k system-locale'
      - '-w /etc/network -p wa -k system-locale'
      - '-w /etc/networks -p wa -k system-locale'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.6

  - name: 4.1.7 Ensure events that modify the system's Mandatory Access Controls are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-w /etc/selinux/ -p wa -k MAC-policy'
      - '-w /etc/apparmor/ -p wa -k MAC-policy'
      - '-w /etc/apparmor.d/ -p wa -k MAC-policy'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.7

  - name: 4.1.8 Ensure login and logout events are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-w /var/log/faillog -p wa -k logins'
      - '-w /var/log/lastlog -p wa -k logins'
      - '-w /var/log/tallylog -p wa -k logins'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.8

  - name: 4.1.9 Ensure session initiation information is collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-w /var/run/utmp -p wa -k session'
      - '-w /var/log/wtmp -p wa -k session'
      - '-w /var/log/btmp -p wa -k session'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.9

  - name: 4.1.10 Ensure discretionary access control permission modification events are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod'
      - '-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod'
      - '-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
      - '-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod'
      - '-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod'
      - '-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' 
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.10

  - name: 4.1.11 Ensure unsuccessful unauthorized file access attempts are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access'
      - '-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access'
      - '-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access'
      - '-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.11

  - shell: "find / -path /sys -prune -o -path /proc -prune -o -path /run -prune -o \\( -perm -4000 -o -perm -2000 \\) -type f|egrep -v '/sys|/proc|/run'"
    register: setuid_setgid_commands
    changed_when: False
    tags:
      - section4
      - section4.1
      - section4.1.12

  - name: 4.1.12 Ensure use of privileged commands is collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: '-a always,exit -F path={{item}} -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged'
      state: present
      create: yes
    with_items: "{{ setuid_setgid_commands.stdout_lines }}"
    when: enable_auditd == True
    notify: restart auditd    
    tags:
      - section4
      - section4.1
      - section4.1.12

  - name: 4.1.13 Ensure successful file system mounts are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts'
      - '-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.13

  - name: 4.1.14 Ensure file deletion events by users are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete'
      - '-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.14

  - name: 4.1.15 Ensure changes to system administration scope (sudoers) is collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-w /etc/sudoers -p wa -k scope'
      - '-w /etc/sudoers.d -p wa -k scope'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.15

  - name: 4.1.16 Ensure system administrator actions (sudolog) are collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: '-w /var/log/sudo.log -p wa -k actions'
      state: present
      create: yes
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.16

  - name: 4.1.17 Ensure kernel module loading and unloading is collected (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: ' {{ item }} '
      state: present
      create: yes
    with_items:
      - '-w /sbin/insmod -p x -k modules'
      - '-w /sbin/rmmod -p x -k modules'
      - '-w /sbin/modprobe -p x -k modules'
      - '-a always,exit -F arch=b64 -S init_module -S delete_module -k modules'
    when: enable_auditd == True
    notify: restart auditd
    tags:
      - section4
      - section4.1
      - section4.1.17

  - name: 4.1.18 Ensure the audit configuration is immutable (Scored)
    lineinfile:
      dest: /etc/audit/audit.rules
      line: '-e 2'
      state: present
      create: yes
      insertafter: EOF
    when: enable_auditd == True
    tags:
      - section4
      - section4.1
      - section4.1.18
