---
- name: Install fail2ban
  apt: pkg=fail2ban state=installed
  tags: package

- name: configure fail2ban local jails
  action: template src=jail.local.j2 dest=/etc/fail2ban/jail.local mode=0644
  notify: restart fail2ban
  tags: configuration

- name: start/stop fail2ban service
  service: name=fail2ban state=started enabled=yes
  tags: service
